services:
  web:
    image: php:8.4-cli
    container_name: pozi_framework
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
